main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('plants/', views.plants_index, name='index'),
    path('plants/<int:plant_id>/', views.plants_detail, name='detail'),
    path('plants/create/', views.PlantCreate.as_view(), name='plants_create'),
    path('plants/<int:pk>/update/', views.PlantUpdate.as_view(), name='plants_update'),
    path('plants/<int:pk>/delete/', views.PlantDelete.as_view(), name='plants_delete'),
    path('plants/<int:plant_id>/add_watering/', views.add_watering, name='add_watering'),
    path('watering/<int:pk>/delete/', views.WateringDelete.as_view(), name='watering_delete'),
    path('soils/', views.SoilList.as_view(), name='soils_index'),
    path('soils/<int:pk>/', views.SoilDetail.as_view(), name='soils_detail'),
    path('soils/create/', views.SoilCreate.as_view(), name='soils_create'),
    path('soils/<int:pk>/update/', views.SoilUpdate.as_view(), name='soils_update'),
    path('soils/<int:pk>/delete/', views.SoilDelete.as_view(), name='soils_delete'),
    path('cats/<int:plant_id>/assoc_soil/<int:soil_id>/', views.assoc_soil, name='assoc_soil'),
    path('cats/<int:plant_id>/remove_soil/<int:soil_id>/', views.remove_soil, name='remove_soil'),
]

plantcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

METHOD = (
    ('T', 'Top-Watering'),
    ('B', 'Bottom-Watering')
)

# Create your models here.
class Soil(models.Model):
    name = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('soil_detail', kwargs={'pk': self.id})

class Plant(models.Model):
    name = models.CharField(max_length=100)
    common_name= models.CharField(max_length=100)
    family = models.TextField(max_length=250)
    soils = models.ManyToManyField(Soil)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'plant_id': self.id})
    
class Watering(models.Model):
    date = models.DateField('Watering Date')
    method = models.CharField(
        max_length=1,
        choices = METHOD,
        default=METHOD[0][0]
        )
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_method_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']
    

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm(ModelForm):
  class Meta:
    model = Watering
    fields = ['date', 'method']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Plant, Watering, Soil
from .forms import WateringForm

# plants = [
#     {'name': 'Monstera Deliciosa', 'common_name': 'swiss cheese plant', 'family': 'Araceae'},
#     {'name': 'Ficus benjamin','common_name': 'Weeping Fig','family': 'Moraceae'},
#     {'name': 'Ficus Lyrata','common_name': 'Fiddle-Leaf Fig','family': 'Moraceae'}
# ]

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def plants_index(request):
    plants = Plant.objects.all()
    return render(request, 'plants/index.html', {'plants' : plants})

def plants_detail(request, plant_id):
  plant = Plant.objects.get(id=plant_id)
  id_list = plant.soils.all().values_list('id')
  soils_plant_doesnt_have = Soil.objects.exclude(id__in=id_list)
  watering_form = WateringForm()
  return render(request, 'plants/detail.html', {
    'plant': plant, 'watering_form': watering_form,
    'soils' : soils_plant_doesnt_have
  })

def assoc_soil(request, plant_id, soil_id):
   Plant.objects.get(id=plant_id).soils.add(soil_id)
   return redirect('detail', plant_id=plant_id)

def remove_soil(request, plant_id, soil_id):
  Plant.objects.get(id=plant_id).soils.remove(soil_id)
  return redirect('detail', plant_id=plant_id)

def add_watering(request, plant_id):
   form = WateringForm(request.POST)
   if form.is_valid():
    new_watering = form.save(commit=False)
    new_watering.plant_id = plant_id
    new_watering.save()
   return redirect('detail', plant_id=plant_id)

class PlantCreate(CreateView):
    model = Plant
    fields = ['name', 'common_name', 'family']

class PlantUpdate(UpdateView):
    model = Plant
    fields = ['common_name', 'family']

class PlantDelete(DeleteView):
    model = Plant
    success_url = '/plants'

class WateringDelete(DeleteView):
    model = Watering
    success_url = '/plants'


class SoilList(ListView):
   model = Soil
   fields = '__all__'

class SoilDetail(DetailView):
   model = Soil
   fields = '__all__'

class SoilCreate(CreateView):
   model = Soil
   fields = '__all__'

class SoilUpdate(UpdateView):
   model = Soil
   fields = ['name', 'brand']

class SoilDelete(DeleteView):
   model = Soil
   success_url = '/soils'
   

   

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Plant Collector</h1>
 <hr>
 <p>Hire the Plant Collector!</p>
 <footer>All Rights Reserved, &copy; 2024 Plant Collector</footer>
</body>
</html>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Plant Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Plant Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'soils_create'%}">Add a Soil</a></li>
          <li><a href="{% url 'soils_index'%}">View All Soils</a></li>
          <li><a href="{% url 'plants_create'%}">Add A Plant</a></li>
          <li><a href="{% url 'index' %}">View All My Plants</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} 
{% block content %}
<h1>HOME</h1>
{% endblock %}

main_app/templates/main_app/plant_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Plant</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' plant.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/plant_form.html
{% extends 'base.html' %}
{% block content %}

{% if object %}
  <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Plant</h1>
{% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/soil_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Soil</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'soils_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/soil_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Soil Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ soil.name }}</span>
        <p>Brand: {{ soil.brand }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'soils_update' soil.id %}">Edit</a>
        <a href="{% url 'soils_delete' soil.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/soil_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Soil</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/soil_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Soil List</h1>

{% for soil in soil_list %}
  <a href="{% url 'soils_detail' soil.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ soil.name }}</span>
            <p>Color: {{ soil.brand }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/watering_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Watering</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ watering.get_method_display }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' object.plant_id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/plants/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ plant.name }}</span>
        <p>Common name: {{ plant.common_name }}</p>
        <p>Family: {{ plant.family }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'plants_update' plant.id %}">Edit</a>
        <a href="{% url 'plants_delete' plant.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_watering' plant.id %}" method="POST">
      {% csrf_token %}
      {{ watering_form.as_p }}
      <input type="submit" class="btn" value="Add Watering">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Method</th></tr>
        <th></th>
      </thead>
      <tbody>
        {% for watering in plant.watering_set.all %}
          <tr>
            <td>{{watering.date}}</td>
            <td>{{watering.get_method_display}}</td>
            <td><a href="{% url 'watering_delete' watering.id %}" class="btn" >Delete</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ plant.name }}'s Soil Mix</h3>
    {% if plant.soils.count %}
      {% for soil in plant.soils.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="brand: {{ soil.brand }}">{{ soil.brand }}</span> {{ soil.name }}
            </span>
            <div class="card-action">
              <form action="{% url 'remove_soil' plant.id soil.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">delete</button>
              </form>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Soil Mix 😿</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Soil options</h3>
    {% if soils.count %}
      {% for soil in soils.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="brand: {{ soil.brand }}">{{ soil.brand }}</span> {{ soil.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_soil' plant.id soil.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{plant.name}} Already Has All Soils Available</h5>
    {% endif %}
  </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
  // M is Materialize's global variable
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_method');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/plants/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Plant List</h1>

{% for plant in plants %}
  <div class="card">
    <a href="{% url 'detail' plant.id %}">
    <div class="card-content">
      <span class="card-title">{{ plant.name }}</span>
      <p>Common Name: {{ plant.common_name }}</p>
      <p>Family: {{ plant.family }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}